# Generated by Django 4.1.3 on 2023-01-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldCupShop', '0003_exercice_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='filename',
        ),
        migrations.AddField(
            model_name='programme',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='exercises'),
        ),
    ]
