# Generated by Django 4.1.3 on 2023-01-25 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worldCupShop', '0004_remove_exercice_filename_remove_programme_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
