# Generated by Django 4.1.3 on 2023-01-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldCupShop', '0005_programme_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='status',
            field=models.CharField(default='private', max_length=50),
        ),
    ]
