# Generated by Django 4.1.3 on 2023-02-03 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldCupShop', '0009_programme_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciceline',
            name='programme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='worldCupShop.programme'),
        ),
        migrations.AlterField(
            model_name='exerciceline',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldCupShop.exerciceimported'),
        ),
    ]
