# Generated by Django 4.1.3 on 2023-02-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldCupShop', '0010_exerciceline_programme_alter_exerciceline_exercice'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciceline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciceline',
            name='order',
            field=models.IntegerField(default=1000),
        ),
    ]
