# Generated by Django 4.1.3 on 2023-02-04 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worldCupShop', '0011_exerciceline_created_at_exerciceline_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionNom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_suggere', models.CharField(max_length=100)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldCupShop.exerciceimported')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
