# Generated by Django 4.1.3 on 2023-02-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldCupShop', '0012_suggestionnom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceLineRepetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serieNumber', models.IntegerField(default=0)),
                ('nbRepetition', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('exerciceLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldCupShop.exerciceline')),
            ],
        ),
    ]
