# Generated by Django 4.1.3 on 2023-02-08 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worldCupShop', '0013_exercicelinerepetition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrainement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldCupShop.programme')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
