# Generated by Django 4.1.3 on 2023-03-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldCupShop', '0014_entrainement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciceline',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldCupShop.programme'),
        ),
    ]
