# Generated by Django 4.1.3 on 2023-03-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldCupShop', '0015_alter_exerciceline_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciceline',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worldCupShop.programme'),
        ),
    ]
